name: Build and Deploy

on:
  workflow_dispatch:
  
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    env:
      TZ: Asia/Tokyo
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          ref: master
      - name: Setup Node
        uses: actions/setup-node@v4.4.0
        with:
          node-version: 23
      - name: Cache deps
        uses: actions/cache@v4.2.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-npm-${{ hashFiles('./package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-
      - name: Install deps
        run: npm ci
      - name: Get Repo name
        id: get-repo-name
        run: |
          REPO=$(echo ${{ github.repository }} | sed -e "s#.*/##")
          echo $REPO
          echo ::set-output name=repo_name::$REPO
      - name: Build
        run: npm run generate
        env:
          PUBLIC_URL: /${{ steps.get-repo-name.outputs.repo_name }}
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4.0.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./.output/public
          publish_branch: gh-pages
